/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum ActKind {
  Expect = 0,
  ExpectError = 1,
  ExitCode = 2,
  Input = 3
}
export interface Act {
  expected: any
  ok: boolean
  actual: any
  kind: ActKind
}
export interface ScenarioResult {
  ok: boolean
}
export function clix(command: string, timeout: number): Scenario
export class Scenario {
  command: string
  timeout: number
  exitCode: number
  acts: Array<Act>
  status: boolean
  constructor(command: string, timeout: number, exitCode: number, acts: Array<Act>, status: boolean)
  expect(value: string): this
  expectError(value: string): this
  exitCode(code: number): this
  input(value: string): this
  run(): Promise<ScenarioResult>
}
