name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  test-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
      env:
        CI: true
    - run: npm run test:unit
      name: Run unit tests
      env:
        CI: true
    - run: npm run test:functional
      name: Run functional tests
      env:
        CI: true
    - run: npm run test:examples
      name: Run example tests
      env:
        CI: true
      
  test-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
      env:
        CI: true
    - run: npm run test:unit
      name: Run unit tests
      env:
        CI: true
    - run: npm run test:functional
      name: Run functional tests
      env:
        CI: true
    - run: npm run test:examples
      name: Run example tests
      env:
        CI: true

